flags: {}
packages:
- '.'
- location:
    git: https://github.com/positiondev/fn
    commit: 6989eca99cc02da5e2268e1aa79157bdd6220ab5
  extra-dep: true
  subdirs:
    - fn
extra-deps:
  - digestive-functors-0.8.2.0
  - directory-1.3.0.0
resolver: lts-8.15
