flags: {}
packages:
- '.'
- location:
    git: https://github.com/positiondev/fn
    commit: 308cda9640db7a78cfc7a89e69e6d9e3e138b24c
  extra-dep: true
  subdirs:
    - fn
extra-deps:
- digestive-functors-0.8.4.0
resolver: lts-12.11
